In [5]:
import numpy as np
from pyDatalog import pyDatalog
from pyDatalog import pyEngine

tb1 = np.array([[0, 0.2, 0.7, 0.8], 
               [0, 0.3, 0.7, 0.5], 
               [0.5, 0.5, 0.5, 0.5],
               [0.7, 0.4, 0.4, 0.6], 
               [0.7, 0.7, 0.3, 0.3]])
tb2 = np.array([[0, 0.3, 0.3, 0.7, 0],
               [0.3, 0.1, 0.7, 0.3, 0.8], 
               [0.8, 0.6, 0.5, 0.4, 0.3], 
               [0.8, 0.8, 0.5, 0.6, 0.2]])

def maxfunc(x, y):
    z = []
    for x1 in x:
        for y1 in y.T:
            z.append(max(np.multiply(x1, y1)))
    return np.array(z).reshape((x.shape[0], y.shape[1]))


print("Армия колдунов: \n")
print("Скелеты: ", tb1[0])
print("Зомби: ", tb1[1])
print("Вампиры: ", tb1[2])
print("Ведьмы: ", tb1[3])
print("Костяной дракон: ", tb1[4], "\n")

print("Армия волшебников: \n")
print("Эф. Магия: ", tb2[0])
print("Эф. Физ. Атак: ", tb2[1])
print("Вос. Магия: ", tb2[2])
print("Вос. Физ. Атак: ", tb2[3], "\n")

print("Эффективность\n")
print(maxfunc(tb1, tb2))

print("А Количество          Б Количество\n")
print("Костянной дракон 1    Крестьяне 2\n")
print("Ведьмы 2              Феи 4\n")
print("Вампиры 3             Эльфы 3\n")
print("Зомби 5               Крестьяне 5\n") 
print("Скелеты 8             Эльфы 8\n")

Армия колдунов: 

Скелеты:  [ 0.   0.2  0.7  0.8]
Зомби:  [ 0.   0.3  0.7  0.5]
Вампиры:  [ 0.5  0.5  0.5  0.5]
Ведьмы:  [ 0.7  0.4  0.4  0.6]
Костяной дракон:  [ 0.7  0.7  0.3  0.3] 

Армия волшебников: 

Эф. Магия:  [ 0.   0.3  0.3  0.7  0. ]
Эф. Физ. Атак:  [ 0.3  0.1  0.7  0.3  0.8]
Вос. Магия:  [ 0.8  0.6  0.5  0.4  0.3]
Вос. Физ. Атак:  [ 0.8  0.8  0.5  0.6  0.2] 

Эффективность

[[ 0.64  0.64  0.4   0.48  0.21]
 [ 0.56  0.42  0.35  0.3   0.24]
 [ 0.4   0.4   0.35  0.35  0.4 ]
 [ 0.48  0.48  0.3   0.49  0.32]
 [ 0.24  0.24  0.49  0.49  0.56]]
А Количество          Б Количество

Костянной дракон 1    Крестьяне 2

Ведьмы 2              Феи 4

Вампиры 3             Эльфы 3

Зомби 5               Крестьяне 5

Скелеты 8             Эльфы 8

